FROM rabbitmq:3-management-alpine

# mqtt 플러그인 사용
RUN rabbitmq-plugins enable rabbitmq_mqtt

COPY rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
RUN chown -R rabbitmq:rabbitmq /var/lib/rabbitmq /etc/rabbitmq &&\
    chmod 777 /var/lib/rabbitmq /etc/rabbitmq