# ---- Runtime ----
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8-alpine3.10 AS runtime

# DB 시작을 기다리기 위한 툴
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

# Guniocorn 설정 파일
ENV GUNICORN_CONF="/app/gunicorn_conf.py"

# App 폴더 생성
WORKDIR /app
COPY ./requirements/deployment.txt ./requirements.txt

# 패키지 설치
RUN pip install -r requirements.txt

# 소스 복사
COPY . /app
